server:
  servlet:
    context-path: ${SERVER_CONTEXT_PATH}
  port: ${SERVER_PORT}
spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
      enabled: on
  main:
    banner-mode: off
  jackson:
    time-zone: UTC
    serialization:
      write-enums-using-to-string: on
      write-dates-as-timestamps: off
      fail-on-empty-beans: off
    default-property-inclusion: always
    deserialization:
      fail-on-unknown-properties: off
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: nls-api
  task:
    scheduling:
      pool:
        size: 20
      threadNamePrefix: nls-task-
      simple:
        concurrency-limit: -1
  profiles:
    active: dev
management:
  endpoints:
    web:
      exposure:
        include: metrics,info,health,restart,refresh,resume
  endpoint:
    health:
      show-details: always
  health:
    mail:
      enabled: on
  info:
    git:
      enabled: on
      mode: full
