server:
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/}
    session:
      timeout: 30m
  port: ${SERVER_PORT:8080}
spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 60MB
      enabled: on
  main:
    banner-mode: off
  messages:
    basename: i18n/messages,i18n/errors,i18n/warnings
  jackson:
    time-zone: UTC
    serialization:
      write-enums-using-to-string: on
      write-dates-as-timestamps: off
      fail-on-empty-beans: off
    default-property-inclusion: always
    deserialization:
      fail-on-unknown-properties: off
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: ${APPLICATION_NAME:nls-api}
  task:
    scheduling:
      pool:
        size: 20
      simple:
        concurrency-limit: -1
management:
  endpoints:
    web:
      exposure:
        include: metrics,info,health,restart,refresh,resume
  endpoint:
    health:
      show-details: always
  health:
    mail:
      enabled: on
  info:
    git:
      enabled: on
      mode: full
